readonly UPDATE_FILE_PATH="${SCRIPT_DIR_PATH}/../../update"
readonly DOCUMENTATION_DIR_PATH="${SCRIPT_DIR_PATH}/../documentation"
readonly MKDOCS_SETTINGS_FILE_PATH="${DOCUMENTATION_DIR_PATH}/mkdocs.yml"
readonly GIT_DEPLOYMENT_BRANCH_NAME='main'
