name: es-vocab

services:
    prod:
        image: es-vocab:prod
        ports:
            - 80:9999
        volumes:
            - type: bind
              source: /root/v1/es-vocab/documentation/site
              target: /var/www/es-vocab/documentation/site
              read_only: true
            - type: bind
              source: /root/v1/update
              target: /var/www/es-vocab/update
        secrets:
            - github_webhook_token
        build: .

    update:
        extends: prod
        image: es-vocab:tmp
        ports:
            - 8080:9999

secrets:
    github_webhook_token:
        file: ../../github_webhook_token
